### ISSUE TITLE
[Buckets] General Page

### ISSUE THREAD

**Issue by evanzummeren** [raditube/tool#14]
This is a general page which shows links to different buckets. Please use ```views/BucketsOverview.vue```

[Design](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-[v2]-—-Front-end?node-id=463%3A1222)

- [x] Private buckets, please use ```public/dummy-data/buckets.json``` private for now.
- [x] Team buckets, please use ```public/dummy-data/buckets.json``` teams for now.
- [x] Community buckets, , please use ```public/dummy-data/buckets.json``` public for now.
- [x] Community buckets must be made searchable through description and keywords.
- [x] All must be linkable to ```buckets/{bucket_id}```. Link hover state is visible in Nairobi journalists for the horizontal items, and in 'hover state example' for the boxes (community)

**Comment by ForceBreak** [comment]
https://github.com/raditube/tool/commit/30f01e4a02f2440ae2692534560f2954d2479034
