### ISSUE TITLE
[Menu bar] Update

### ISSUE THREAD

**Issue by evanzummeren** [raditube/tool#16]
Some small, mostly visual updates to the menu bar. Current menu bar can be found in components feature nav.
[Design](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-[v2]-—-Front-end?node-id=463%3A1222) (see top)

- [x] If router link is active, make that text Demi. (See Buckets). Inactive links become grayish (#888888).

-- Update

- [x] Fix logo (position, grayish)
- [x] Add consultancy button on the right [design](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-[v2]-—-Front-end?node-id=463%3A1222). Make this linkable to https://www.raditube.com

**Comment by ForceBreak** [comment]
https://github.com/raditube/tool/commit/49571e110055faa4f45c1674266f6898b9754318

**Comment by ForceBreak** [comment]
https://github.com/raditube/tool/commit/dcfda3b3ce3ed0bffc60f64b9fe21f3d13895014

**Comment by evanzummeren** [comment]
- [ ] Fix logo (position, grayish)
- [ ] Add consultancy button on the right [design](https://www.figma.com/file/0bXahS6yhrW0KxWX8054YE/Tool-[v2]-—-Front-end?node-id=463%3A1222)
